//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use objc2::extern_protocol;
use objc2::rc::Retained;
use objc2_foundation::{NSObjectProtocol, NSString};

use crate::*;

extern_protocol!(
    /// Represents a binary function.
    ///
    /// A binary function is a shader that you precompile from Metal IR to GPU machine code.
    ///
    /// See also [Apple's documentation](https://developer.apple.com/documentation/metal/mtl4binaryfunction?language=objc)
    pub unsafe trait MTL4BinaryFunction: NSObjectProtocol + Send + Sync {
        /// Obtains the optional name of this binary function.
        #[unsafe(method(name))]
        #[unsafe(method_family = none)]
        unsafe fn name(&self) -> Option<Retained<NSString>>;

        /// Describes the type of this binary function.
        #[unsafe(method(functionType))]
        #[unsafe(method_family = none)]
        unsafe fn functionType(&self) -> MTLFunctionType;
    }
);
