mod constants;
mod tensor;
mod tensor_auxiliary_plane;
mod tensor_auxiliary_plane_descriptor;
mod tensor_auxiliary_plane_descriptor_map;
mod tensor_buffer_attachments;
mod tensor_data_type;
mod tensor_descriptor;
mod tensor_error;
mod tensor_extents;
mod tensor_plane_type;
mod tensor_reference_type;
mod tensor_usage;

pub use constants::TENSOR_MAX_RANK;
pub use tensor::{MTLTensor, MTLTensorExt};
pub use tensor_auxiliary_plane::MTLTensorAuxiliaryPlane;
pub use tensor_auxiliary_plane_descriptor::MTLTensorAuxiliaryPlaneDescriptor;
pub use tensor_auxiliary_plane_descriptor_map::MTLTensorAuxiliaryPlaneDescriptorMap;
pub use tensor_buffer_attachments::MTLTensorBufferAttachments;
pub use tensor_data_type::MTLTensorDataType;
pub use tensor_descriptor::MTLTensorDescriptor;
pub use tensor_error::{MTLTensorError, tensor_error_domain};
pub use tensor_extents::MTLTensorExtents;
pub use tensor_plane_type::MTLTensorPlaneType;
pub use tensor_reference_type::MTLTensorReferenceType;
pub use tensor_usage::MTLTensorUsage;
