mod pass_descriptor;
mod sample_buffer_attachment_descriptor;
mod sample_buffer_attachment_descriptor_array;

pub use pass_descriptor::MTLAccelerationStructurePassDescriptor;
pub use sample_buffer_attachment_descriptor::MTLAccelerationStructurePassSampleBufferAttachmentDescriptor;
pub use sample_buffer_attachment_descriptor_array::MTLAccelerationStructurePassSampleBufferAttachmentDescriptorArray;
